# Generated by Django 4.2.18 on 2025-02-14 17:24

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Jogging Event', max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('Urban', 'Urban'), ('Trail', 'Trail'), ('Track', 'Track'), ('Canals', 'Canals'), ('Coffee', 'Coffee')], default='Urban', max_length=6)),
                ('distance', models.FloatField(default=0.0)),
                ('distance_unit', models.CharField(choices=[('KM', 'Kilometers'), ('MI', 'Miles')], default='KM', max_length=2)),
                ('time', models.TimeField(default=None, null=True)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday')),
                ('location_short', models.CharField(default='Birmingham', max_length=100)),
                ('location', models.CharField(default='Birmingham, City Centre, B1 1AA', max_length=100)),
                ('location_url', models.URLField(blank=True, default='https://maps.app.goo.gl/j4xrUjyJCYmN6guS9')),
                ('body', models.TextField(max_length=300)),
                ('background_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('icon', models.TextField(default='fa-solid fa-city', max_length=300)),
                ('banner_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
