# Generated by Django 4.2.18 on 2025-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='day',
        ),
        migrations.RemoveField(
            model_name='post',
            name='notifications',
        ),
        migrations.AddField(
            model_name='post',
            name='day_and_time',
            field=models.DateTimeField(default='2021-01-01 00:00:00', max_length=100),
        ),
    ]
