# Generated by Django 4.2.18 on 2025-02-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Mon', max_length=3),
        ),
    ]
