# Generated by Django 4.2.18 on 2025-02-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='day_int',
            field=models.IntegerField(default=0),
        ),
    ]
