# Generated by Django 4.2.18 on 2025-02-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0002_post_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday'),
        ),
    ]
