# Generated by Django 4.2.18 on 2025-02-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0003_alter_post_day_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='distance_unit',
            field=models.CharField(choices=[('KM', 'Kilometers'), ('MI', 'Miles')], default='KM', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
