# Generated by Django 4.2.18 on 2025-02-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0003_alter_post_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='icon',
            field=models.TextField(default='fa-solid fa-city', max_length=300),
        ),
    ]
