# Generated by Django 4.2.18 on 2025-02-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0003_post_day_int'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
