# Generated by Django 4.2.18 on 2025-02-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0004_post_distance_unit_alter_post_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Trail', 'Trail'), ('Coffee', 'Coffee')], default='Urban', max_length=6),
        ),
    ]
