# Generated by Django 4.2.18 on 2025-02-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0005_post_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location_url',
            field=models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4859.76259087934!2d-1.89809485!3d52.481284949999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4870bc8dea5a590b%3A0xf5a8185ddef9e97c!2sCity%20Centre%2C%20Birmingham!5e0!3m2!1sen!2suk!4v1739799821808!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade', max_length=1000),
        ),
    ]
