# Generated by Django 4.2.18 on 2025-02-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0006_alter_post_location_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
