# Generated by Django 4.2.18 on 2025-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0006_alter_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Jogging Event', max_length=100),
        ),
    ]
