# Generated by Django 4.2.18 on 2025-02-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0007_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile_image',
        ),
    ]
