# Generated by Django 4.2.18 on 2025-02-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_post', '0008_remove_comment_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Trail', 'Trail'), ('Track', 'Track'), ('Canals', 'Canals'), ('Coffee', 'Coffee')], default='Urban', max_length=6),
        ),
    ]
